### ISSUE TITLE
Mjolnir docs incorrectly claim that the WordList feature supports regexps

### ISSUE THREAD

**Issue by PC-Admin** [matrix-org/mjolnir#539]
This is a bit of a strange one. Running quite bleeding edge Synapse/Mjolnir using the common matrix-docker-ansible-deploy tool.

Trying to configure Mjolnir's wordlist feature today, we're getting too many spammers posting t.me links.

For example a link might look like: https://t.me/+f4f0UGib4TFiMDde

Tried all of these regexp's to try and match it, strangely none of them do:
```
protections:
  wordlist:
    minutesBeforeTrusting: 1440
    words:
    - 'https://t.me/.*'
    - 'https\:\/\/t.me\/.*'
    - 't.me\/'
    - '.*t.me\/.*'
    - '.*t\.me\/.*'
    - 't\.me\/.*'
    - 'jumanji'
```

The word 'jumanji' works fine however.

Does anyone know what I'm doing wrong here? Or is this perhaps a bug with Mjolnir?
